controller_list:
  - name: fake_left_arm_controller
    joints:
      - LARM_JOINT0
      - LARM_JOINT1
      - LARM_JOINT2
      - LARM_JOINT3
      - LARM_JOINT4
      - LARM_JOINT5
      - LARM_JOINT6
  - name: fake_left_arm_torso_controller
    joints:
      - CHEST_JOINT0
      - CHEST_JOINT1
      - LARM_JOINT0
      - LARM_JOINT1
      - LARM_JOINT2
      - LARM_JOINT3
      - LARM_JOINT4
      - LARM_JOINT5
      - LARM_JOINT6
  - name: fake_head_controller
    joints:
      - HEAD_JOINT0
      - HEAD_JOINT1
  - name: fake_right_arm_controller
    joints:
      - RARM_JOINT0
      - RARM_JOINT1
      - RARM_JOINT2
      - RARM_JOINT3
      - RARM_JOINT4
      - RARM_JOINT5
      - RARM_JOINT6
  - name: fake_right_arm_torso_controller
    joints:
      - CHEST_JOINT0
      - CHEST_JOINT1
      - RARM_JOINT0
      - RARM_JOINT1
      - RARM_JOINT2
      - RARM_JOINT3
      - RARM_JOINT4
      - RARM_JOINT5
      - RARM_JOINT6
  - name: fake_whole_body_controller
    joints:
      - virtual_joint
      - CHEST_JOINT0
      - CHEST_JOINT1
      - LARM_JOINT0
      - LARM_JOINT1
      - LARM_JOINT2
      - LARM_JOINT3
      - LARM_JOINT4
      - LARM_JOINT5
      - LARM_JOINT6
      - RARM_JOINT0
      - RARM_JOINT1
      - RARM_JOINT2
      - RARM_JOINT3
      - RARM_JOINT4
      - RARM_JOINT5
      - RARM_JOINT6
      - LLEG_JOINT0
      - LLEG_JOINT1
      - LLEG_JOINT2
      - LLEG_JOINT3
      - LLEG_JOINT4
      - LLEG_JOINT5
      - LLEG_JOINT6
      - RLEG_JOINT0
      - RLEG_JOINT1
      - RLEG_JOINT2
      - RLEG_JOINT3
      - RLEG_JOINT4
      - RLEG_JOINT5
      - RLEG_JOINT6
  - name: fake_whole_body_fixed_controller
    joints:
      - CHEST_JOINT0
      - CHEST_JOINT1
      - LARM_JOINT0
      - LARM_JOINT1
      - LARM_JOINT2
      - LARM_JOINT3
      - LARM_JOINT4
      - LARM_JOINT5
      - LARM_JOINT6
      - RARM_JOINT0
      - RARM_JOINT1
      - RARM_JOINT2
      - RARM_JOINT3
      - RARM_JOINT4
      - RARM_JOINT5
      - RARM_JOINT6
      - LLEG_JOINT0
      - LLEG_JOINT1
      - LLEG_JOINT2
      - LLEG_JOINT3
      - LLEG_JOINT4
      - LLEG_JOINT5
      - RLEG_JOINT0
      - RLEG_JOINT1
      - RLEG_JOINT2
      - RLEG_JOINT3
      - RLEG_JOINT4
      - RLEG_JOINT5
  - name: fake_left_hand_controller
    joints:
      - L_INDEXMP_R
      - L_INDEXMP_P
      - L_INDEXPIP_R
      - L_MIDDLEPIP_R
      - L_THUMBCM_Y
      - L_THUMBCM_P
  - name: fake_right_hand_controller
    joints:
      - R_INDEXMP_R
      - R_INDEXMP_P
      - R_INDEXPIP_R
      - R_MIDDLEPIP_R
      - R_THUMBCM_Y
      - R_THUMBCM_P
  - name: fake_left_foot_controller
    joints:
      - LLEG_JOINT6
  - name: fake_right_foot_controller
    joints:
      - RLEG_JOINT6
  - name: fake_left_leg_controller
    joints:
      - LLEG_JOINT0
      - LLEG_JOINT1
      - LLEG_JOINT2
      - LLEG_JOINT3
      - LLEG_JOINT4
      - LLEG_JOINT5
  - name: fake_right_leg_controller
    joints:
      - RLEG_JOINT0
      - RLEG_JOINT1
      - RLEG_JOINT2
      - RLEG_JOINT3
      - RLEG_JOINT4
      - RLEG_JOINT5
  - name: fake_upper_body_controller
    joints:
      - CHEST_JOINT0
      - CHEST_JOINT1
      - LARM_JOINT0
      - LARM_JOINT1
      - LARM_JOINT2
      - LARM_JOINT3
      - LARM_JOINT4
      - LARM_JOINT5
      - LARM_JOINT6
      - RARM_JOINT0
      - RARM_JOINT1
      - RARM_JOINT2
      - RARM_JOINT3
      - RARM_JOINT4
      - RARM_JOINT5
      - RARM_JOINT6
  - name: fake_torso_controller
    joints:
      - CHEST_JOINT0
      - CHEST_JOINT1
  - name: fake_robot_joints_controller
    joints:
      - CHEST_JOINT0
      - CHEST_JOINT1
      - HEAD_JOINT0
      - HEAD_JOINT1
      - LARM_JOINT0
      - LARM_JOINT1
      - LARM_JOINT2
      - LARM_JOINT3
      - LARM_JOINT4
      - LARM_JOINT5
      - LARM_JOINT6
      - LARM_JOINT7
      - L_INDEXMP_R
      - L_INDEXMP_P
      - L_INDEXPIP_R
      - L_MIDDLEPIP_R
      - L_THUMBCM_Y
      - L_THUMBCM_P
      - RARM_JOINT0
      - RARM_JOINT1
      - RARM_JOINT2
      - RARM_JOINT3
      - RARM_JOINT4
      - RARM_JOINT5
      - RARM_JOINT6
      - RARM_JOINT7
      - R_INDEXMP_R
      - R_INDEXMP_P
      - R_INDEXPIP_R
      - R_MIDDLEPIP_R
      - R_THUMBCM_Y
      - R_THUMBCM_P
      - LLEG_JOINT0
      - LLEG_JOINT1
      - LLEG_JOINT2
      - LLEG_JOINT3
      - LLEG_JOINT4
      - LLEG_JOINT5
      - LLEG_JOINT6
      - RLEG_JOINT0
      - RLEG_JOINT1
      - RLEG_JOINT2
      - RLEG_JOINT3
      - RLEG_JOINT4
      - RLEG_JOINT5
      - RLEG_JOINT6
  - name: fake_whole_body_minus_left_leg_controller
    joints:
      - CHEST_JOINT0
      - CHEST_JOINT1
      - LARM_JOINT0
      - LARM_JOINT1
      - LARM_JOINT2
      - LARM_JOINT3
      - LARM_JOINT4
      - LARM_JOINT5
      - LARM_JOINT6
      - RARM_JOINT0
      - RARM_JOINT1
      - RARM_JOINT2
      - RARM_JOINT3
      - RARM_JOINT4
      - RARM_JOINT5
      - RARM_JOINT6
      - RLEG_JOINT0
      - RLEG_JOINT1
      - RLEG_JOINT2
      - RLEG_JOINT3
      - RLEG_JOINT4
      - RLEG_JOINT5