# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
# Finally, as a final step velocity limits can be scaled using a global value [velocity_scaling_factor]
joint_limits:
  velocity_scaling_factor: 0.1
  virtual_joint:
    trans_x:
      has_velocity_limits: true
      max_velocity: 0.1
      has_acceleration_limits: false
      max_acceleration: 1
    trans_y:
      has_velocity_limits: true
      max_velocity: 0.1
      has_acceleration_limits: false
      max_acceleration: 1
    trans_z:
      has_velocity_limits: true
      max_velocity: 0.1
      has_acceleration_limits: false
      max_acceleration: 1
    rot_x:
      has_velocity_limits: true
      max_velocity: 0.1
      has_acceleration_limits: false
      max_acceleration: 1
    rot_y:
      has_velocity_limits: true
      max_velocity: 0.1
      has_acceleration_limits: false
      max_acceleration: 1
    rot_z:
      has_velocity_limits: true
      max_velocity: 0.1
      has_acceleration_limits: false
      max_acceleration: 1
    rot_w:
      has_velocity_limits: true
      max_velocity: 0.1
      has_acceleration_limits: false
      max_acceleration: 1
  CHEST_JOINT0:
    has_velocity_limits: true
    max_velocity: 4.40217
    has_acceleration_limits: false
    max_acceleration: 0
  CHEST_JOINT1:
    has_velocity_limits: true
    max_velocity: 2.3963
    has_acceleration_limits: false
    max_acceleration: 0
  HEAD_JOINT0:
    has_velocity_limits: true
    max_velocity: 6.87679
    has_acceleration_limits: false
    max_acceleration: 0
  HEAD_JOINT1:
    has_velocity_limits: true
    max_velocity: 6.87679
    has_acceleration_limits: false
    max_acceleration: 0
  LARM_JOINT0:
    has_velocity_limits: true
    max_velocity: 4.17044
    has_acceleration_limits: false
    max_acceleration: 0
  LARM_JOINT1:
    has_velocity_limits: true
    max_velocity: 2.4192
    has_acceleration_limits: false
    max_acceleration: 0
  LARM_JOINT2:
    has_velocity_limits: true
    max_velocity: 4.15699
    has_acceleration_limits: false
    max_acceleration: 0
  LARM_JOINT3:
    has_velocity_limits: true
    max_velocity: 2.23776
    has_acceleration_limits: false
    max_acceleration: 0
  LARM_JOINT4:
    has_velocity_limits: true
    max_velocity: 4.72794
    has_acceleration_limits: false
    max_acceleration: 0
  LARM_JOINT5:
    has_velocity_limits: true
    max_velocity: 6.63609
    has_acceleration_limits: false
    max_acceleration: 0
  LARM_JOINT6:
    has_velocity_limits: true
    max_velocity: 2.77088
    has_acceleration_limits: false
    max_acceleration: 0
  LARM_JOINT7:
    has_velocity_limits: true
    max_velocity: 4.72794
    has_acceleration_limits: false
    max_acceleration: 0
  LLEG_JOINT0:
    has_velocity_limits: true
    max_velocity: 3.54108
    has_acceleration_limits: false
    max_acceleration: 0
  LLEG_JOINT1:
    has_velocity_limits: true
    max_velocity: 3.80952
    has_acceleration_limits: false
    max_acceleration: 0
  LLEG_JOINT2:
    has_velocity_limits: true
    max_velocity: 4.42233
    has_acceleration_limits: false
    max_acceleration: 0
  LLEG_JOINT3:
    has_velocity_limits: true
    max_velocity: 3.9801
    has_acceleration_limits: false
    max_acceleration: 0
  LLEG_JOINT4:
    has_velocity_limits: true
    max_velocity: 5.07937
    has_acceleration_limits: false
    max_acceleration: 0
  LLEG_JOINT5:
    has_velocity_limits: true
    max_velocity: 9.14286
    has_acceleration_limits: false
    max_acceleration: 0
  LLEG_JOINT6:
    has_velocity_limits: true
    max_velocity: 8.85929
    has_acceleration_limits: false
    max_acceleration: 0
  RARM_JOINT0:
    has_velocity_limits: true
    max_velocity: 4.17044
    has_acceleration_limits: false
    max_acceleration: 0
  RARM_JOINT1:
    has_velocity_limits: true
    max_velocity: 2.4192
    has_acceleration_limits: false
    max_acceleration: 0
  RARM_JOINT2:
    has_velocity_limits: true
    max_velocity: 4.15699
    has_acceleration_limits: false
    max_acceleration: 0
  RARM_JOINT3:
    has_velocity_limits: true
    max_velocity: 2.23776
    has_acceleration_limits: false
    max_acceleration: 0
  RARM_JOINT4:
    has_velocity_limits: true
    max_velocity: 4.72794
    has_acceleration_limits: false
    max_acceleration: 0
  RARM_JOINT5:
    has_velocity_limits: true
    max_velocity: 6.63609
    has_acceleration_limits: false
    max_acceleration: 0
  RARM_JOINT6:
    has_velocity_limits: true
    max_velocity: 2.77088
    has_acceleration_limits: false
    max_acceleration: 0
  RARM_JOINT7:
    has_velocity_limits: true
    max_velocity: 4.72794
    has_acceleration_limits: false
    max_acceleration: 0
  RLEG_JOINT0:
    has_velocity_limits: true
    max_velocity: 3.54108
    has_acceleration_limits: false
    max_acceleration: 0
  RLEG_JOINT1:
    has_velocity_limits: true
    max_velocity: 3.80952
    has_acceleration_limits: false
    max_acceleration: 0
  RLEG_JOINT2:
    has_velocity_limits: true
    max_velocity: 4.42233
    has_acceleration_limits: false
    max_acceleration: 0
  RLEG_JOINT3:
    has_velocity_limits: true
    max_velocity: 3.9801
    has_acceleration_limits: false
    max_acceleration: 0
  RLEG_JOINT4:
    has_velocity_limits: true
    max_velocity: 5.07937
    has_acceleration_limits: false
    max_acceleration: 0
  RLEG_JOINT5:
    has_velocity_limits: true
    max_velocity: 9.14286
    has_acceleration_limits: false
    max_acceleration: 0
  RLEG_JOINT6:
    has_velocity_limits: true
    max_velocity: 8.85929
    has_acceleration_limits: false
    max_acceleration: 0