upper_body:
  kinematics_solver: whole_body_kinematics_plugin/WholeBodyKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 2
  kinematics_solver_attempts: 1
  kinematics_solver_ik_links:
    - RARM_LINK6
    - LARM_LINK6
#    - RLEG_LINK5
#    - LLEG_LINK5
